# Generated by Django 5.2 on 2025-04-13 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='photo',
            field=models.FileField(upload_to='uploads/'),
        ),
    ]
