# Generated by Django 5.2 on 2025-04-21 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0003_datasets'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chart_Types',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chart_type', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Charts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_type', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.chart_types')),
                ('dataset', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.datasets')),
            ],
        ),
        migrations.CreateModel(
            name='Dashboards',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('status', models.BooleanField()),
                ('create_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('chart_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.charts')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.users')),
            ],
        ),
        migrations.AddField(
            model_name='charts',
            name='dashboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.dashboards'),
        ),
    ]
