# Generated by Django 5.2 on 2025-04-22 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0005_alter_dashboards_user_id_alter_datasets_user_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='dashboards',
            old_name='chart_id',
            new_name='chart',
        ),
        migrations.RenameField(
            model_name='dashboards',
            old_name='user_id',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='datasets',
            old_name='user_id',
            new_name='user',
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='name',
            field=models.CharField(default='Untitled Dashboard', max_length=255),
        ),
        migrations.AlterField(
            model_name='dashboards',
            name='status',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='role',
            field=models.ForeignKey(default=2, null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.roles'),
        ),
    ]
