# Generated by Django 5.2 on 2025-05-12 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0010_dataset_columns_selected_columns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='chart',
        ),
    ]
