# Generated by Django 5.2 on 2025-05-12 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0011_remove_dashboards_chart'),
    ]

    operations = [
        migrations.AddField(
            model_name='charts',
            name='description',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='charts',
            name='title',
            field=models.CharField(default='Untitled Chart', max_length=255),
        ),
    ]
