# Generated by Django 5.2 on 2025-05-12 01:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0012_charts_description_charts_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='title',
        ),
        migrations.AddField(
            model_name='dashboards',
            name='chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.charts'),
        ),
    ]
