# Generated by Django 5.2 on 2025-05-12 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0013_remove_charts_description_remove_charts_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dashboards',
            name='chart',
        ),
    ]
