# Generated by Django 5.2 on 2025-05-13 07:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insighthubapp', '0015_charts_description_charts_name_charts_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='charts',
            name='description',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='name',
        ),
        migrations.RemoveField(
            model_name='charts',
            name='user',
        ),
        migrations.AddField(
            model_name='dashboards',
            name='chart',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='insighthubapp.charts'),
        ),
    ]
